import 'package:get_it/get_it.dart';

final instance = GetIt.instance;

Future<void> initAppModule() async {

}
/*
I/flutter ( 1252): 🔄 ConsumptionLimitCubit: Resetting to initial state
I/flutter ( 1252): ✅ All auth data cleared (SharedPreferences + GlobalState + NetworkService + HydratedBloc + Plans + PlansCache + HomeCubits)
I/flutter ( 1252): ✅ Logout: All auth data cleared

======== Exception caught by widgets library =======================================================
The following assertion was thrown building ValueListenableBuilder<Object?>(state: _ValueListenableBuilderState<Object?>#0ce5e):
There should be exactly one item with [DropdownButton]'s value: 2428999875. 
Either zero or 2 or more [DropdownItem]s were detected with the same value
'package:dropdown_button2/src/utils.dart':
Failed assertion: line 20 pos 5: 'valueListenable?.value == null ||
        items.where((DropdownItem<T> item) {
              return item.value == valueListenable!.value;
            }).length ==
            1'

The relevant error-causing widget was: 
  ValueListenableBuilder<Object?> ValueListenableBuilder:file:///Users/nahin/.pub-cache/hosted/pub.dev/dropdown_button2-3.0.0/lib/src/dropdown_button2.dart:818:11
When the exception was thrown, this was the stack: 
#2      _uniqueValueAssert (package:dropdown_button2/src/utils.dart:20:5)
#3      _DropdownButton2State.build.<anonymous closure> (package:dropdown_button2/src/dropdown_button2.dart:822:15)
#4      _ValueListenableBuilderState.build (package:flutter/src/widgets/value_listenable_builder.dart:143:26)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5931:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5817:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#13     ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#15     Element.updateChildren (package:flutter/src/widgets/framework.dart:4191:32)
#16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7295:17)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#24     StatelessElement.update (package:flutter/src/widgets/framework.dart:5895:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#32     StatelessElement.update (package:flutter/src/widgets/framework.dart:5895:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#39     StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#43     StatelessElement.update (package:flutter/src/widgets/framework.dart:5895:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#49     ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#53     StatelessElement.update (package:flutter/src/widgets/framework.dart:5895:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#61     ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#62     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:108:11)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#67     StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#71     ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#76     StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#80     ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#85     StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#89     StatelessElement.update (package:flutter/src/widgets/framework.dart:5895:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#98     StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#100    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#103    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#105    StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#109    ProxyElement.update (package:flutter/src/widgets/framework.dart:6149:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7122:14)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#119    StatelessElement.update (package:flutter/src/widgets/framework.dart:5895:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:6007:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:4037:15)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5841:16)
#127    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5982:11)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:5529:7)
#129    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2750:15)
#130    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2807:11)
#131    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3111:18)
#132    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1302:21)
#133    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
#134    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1430:15)
#135    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1345:9)
#136    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1198:5)
#137    _invoke (dart:ui/hooks.dart:356:13)
#138    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444:5)
#139    _drawFrame (dart:ui/hooks.dart:328:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
W/WindowOnBackDispatcher( 1252): sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@8f93631
W/WindowOnBackDispatcher( 1252): sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@8f93631
*/